sudo: required
dist: trusty
env:
- OS=ubuntu DIST=xenial ARCH=amd64
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-get --yes install dh-autoreconf pkg-kde-tools
- wget --directory-prefix=/tmp https://raw.githubusercontent.com/ev3dev/ev3dev-buildscripts/master/pbuilder-ev3dev
- chmod +x /tmp/pbuilder-ev3dev
- "/tmp/pbuilder-ev3dev deps"
before_script:
- "/tmp/pbuilder-ev3dev base"
- git checkout -b ev3dev-$DIST
script:
- "/tmp/pbuilder-ev3dev build"
before_deploy:
- LICENSES='"LGPL-2.1", "GPL-2.0", "MIT"'
- "/tmp/pbuilder-ev3dev dpl"
deploy:
  on:
    tags: true
  provider: bintray
  file: "$HOME/bintray.json"
  user: dlech
  key:
    secure: ROabMjqJMMwQvNBJ30Ym+MBpXslQ3qNlOpjpYw/f1kIkKvHWnKkMjK9C/nUjPOyKA/P5r3dnAQDnXgOA/FrUTGk8UA8oq/rNhgNalbQ2V+gxHQOLcXslqVC5HqSrt8cUS45YwqHzPekvb+uOAOFvnarn+wHLqcjOQ/FB+QOhHqkCkFoWPU6iymU0FS/nx7Hgq6BFR/Log5JCXzn81fuH/c8AbjbnzCY0XZpK5lbGAyXJSRdDK+LwHWFEhFuLdNWMyk16DOgTcZnSOj2E5rU7sXRYjcXoSBS/BPwdAMfaaQpgVp/diExEgYOfaxrHGW8ohZDVjbiEql4fA6NFnGycbLImkztG49oXoSJH6A0LbeQiUnHw+rBENm4NdnGSBhWhQV91O99axqkYqMFHhGl88BU+/LIT56eeiVhB13gAhG0zm4i2Xs2mnxKIntXN5gRHEZItE+jzuoYiPXSKNnxk4gsN1OUnN3gUFFIXEfFDTI/mz2CN9lQ7xg/voAdv4P2J3QqxZQm3tytEwp0/W96YBf3gIOaQLNeZ3RLM3pOyB/NDARHhBZczGQkYHfoYoVFUTpeSkHzIMn5/Kmk658xHiLw5sw8H5i0hhpxwlriSwNWSAHndwkClSRSn6+zIzaNP8a3DGlVaTH08a+VPK4v/ofQXEErSvAt83CLCZ5IU0iE=
